language: python
python:
  - "3.6.5"
cache: pip
env: 
  - DJANGO=1.11
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source='.' manage.py test -v 2
after_success:
  - coveralls