language: python
python:
  - "3.6.5"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source='.' ./manage.py test --settings=settings.test
after_success:
  - coveralls